/*
POSIX_UI_FONT.C

The overlay's fonts (ui_overlay.c; configure.py --game-browser,
HALO_GAME_BROWSER): TrueType faces built into the game (port/linux/ui/fonts,
as data the build generates), measured and rasterised with stb_truetype
(port/third_party/stb). Compiled with the host's ABI, as the posix_*.c are:
stb is ordinary C that expects it (on Android, in the guest, with the
overlay).
*/

#ifdef HALO_GAME_BROWSER

#include "ui_font.h"

#include <math.h>
#include <stdlib.h>
#include <string.h>

#define STB_TRUETYPE_IMPLEMENTATION
#define STBTT_STATIC
#include "stb_truetype.h"

/* the fonts' data (tools/embed_assets.py --fonts, generated by the build:
32-bit words, which every build's assembly carries as they are) */
extern const unsigned int *const ui_font_files[POSIX_UI_FONT_COUNT];
#define font_data ((const unsigned char *const *)ui_font_files)

static struct
{
	int state; /* 0 not tried, 1 ready, -1 broken */
	stbtt_fontinfo info;
} fonts[POSIX_UI_FONT_COUNT];

/* The themes' faces' capitals are shorter than Noto Sans's for the same
pixel height (cap height over ascent plus descent: Rajdhani's 0.504,
Titillium Web's 0.450, against 0.524), so they are drawn this much bigger
to keep the overlay's text the same size. */
#define GLASSED_SIZE_SCALE 1.04f
#define CAIRO_SIZE_SCALE 1.164f

/* the scale from font units to pixels for a pixel height */
static float pixel_scale(stbtt_fontinfo *info, int font, float pixel_height)
{
	if (font == POSIX_UI_FONT_GLASSED_REGULAR || font == POSIX_UI_FONT_GLASSED_BOLD)
		pixel_height *= GLASSED_SIZE_SCALE;
	else if (font == POSIX_UI_FONT_CAIRO_REGULAR || font == POSIX_UI_FONT_CAIRO_BOLD)
		pixel_height *= CAIRO_SIZE_SCALE;
	return stbtt_ScaleForPixelHeight(info, pixel_height);
}

static stbtt_fontinfo *face(int font)
{
	if (font < 0 || font >= POSIX_UI_FONT_COUNT)
		return NULL;
	if (!fonts[font].state)
	{
		const unsigned char *data = font_data[font];
		int offset = stbtt_GetFontOffsetForIndex(data, 0);

		fonts[font].state = offset >= 0 && stbtt_InitFont(&fonts[font].info, data, offset) ? 1 : -1;
	}
	return fonts[font].state > 0 ? &fonts[font].info : NULL;
}

int posix_ui_font_metrics(int font, float pixel_height, float *ascent, float *descent)
{
	stbtt_fontinfo *info = face(font);
	int ascent_units, descent_units, gap_units;
	float scale;

	if (!info)
		return 0;
	scale = pixel_scale(info, font, pixel_height);
	stbtt_GetFontVMetrics(info, &ascent_units, &descent_units, &gap_units);
	*ascent = (float)ascent_units * scale;
	*descent = (float)-descent_units * scale;
	return 1;
}

int posix_ui_font_has(int font, unsigned int codepoint)
{
	stbtt_fontinfo *info = face(font);

	return info && stbtt_FindGlyphIndex(info, (int)codepoint) != 0;
}

float posix_ui_font_advance(int font, float pixel_height, unsigned int codepoint, unsigned int previous)
{
	stbtt_fontinfo *info = face(font);
	int advance, bearing;
	float scale, width;

	if (!info)
		return 0.0f;
	scale = pixel_scale(info, font, pixel_height);
	stbtt_GetCodepointHMetrics(info, (int)codepoint, &advance, &bearing);
	width = (float)advance * scale;
	if (previous)
		width += (float)stbtt_GetCodepointKernAdvance(info, (int)previous, (int)codepoint) * scale;
	return width;
}

unsigned char *posix_ui_font_glyph(int font, float pixel_height, unsigned int codepoint, int *width, int *height,
	int *x_offset, int *y_offset)
{
	stbtt_fontinfo *info = face(font);

	*width = *height = *x_offset = *y_offset = 0;
	if (!info)
		return NULL;
	return stbtt_GetCodepointBitmap(info, 0, pixel_scale(info, font, pixel_height), (int)codepoint,
		width, height, x_offset, y_offset);
}

void posix_ui_font_free(unsigned char *bitmap)
{
	stbtt_FreeBitmap(bitmap, NULL);
}

#endif
