/*
DIALOGUE_DEFINITIONS.C
*/

/* ---------- headers */

#include "units/dialogue_definitions.h"

/* ---------- globals */

char const *dialogue_vocalization_type_name[NUMBER_OF_DIALOGUE_VOCALIZATION_TYPES][2] =
{
	{ "idle noncombat", "idle noncom" },
	{ "idle combat", "idle combat" },
	{ "idle flee", "idle flee" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "pain body minor", "p b minor" },
	{ "pain body major", "p b major" },
	{ "pain shield", "p shield" },
	{ "pain falling", "p fall" },
	{ "scream fear", "scream fear" },
	{ "scream pain", "scream pain" },
	{ "maimed limb", "maim limb" },
	{ "maimed head", "maim head" },
	{ "death quiet", "d quiet" },
	{ "death violent", "d viol" },
	{ "death falling", "d fall" },
	{ "death agonizing", "d agony" },
	{ "death instant", "d inst" },
	{ "death flying", "d flying" },
	{ "unused", "unused" },
	{ "damaged friend", "s fri" },
	{ "damaged friend player", "s playr" },
	{ "damaged enemy", "s enemy" },
	{ "damaged enemy cm", "s en cm" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "hurt friend", "h fri" },
	{ "hurt friend re", "h fri re" },
	{ "hurt friend player", "h playr" },
	{ "hurt enemy", "h enemy" },
	{ "hurt enemy re", "h en re" },
	{ "hurt enemy cm", "h en cm" },
	{ "hurt enemy bullet", "h en bull" },
	{ "hurt enemy needler", "h en need" },
	{ "hurt enemy plasma", "h en plas" },
	{ "hurt enemy sniper", "h en snipe" },
	{ "hurt enemy grenade", "h en gren" },
	{ "hurt enemy explosion", "h en expl" },
	{ "hurt enemy melee", "h en melee" },
	{ "hurt enemy flame", "h en flame" },
	{ "hurt enemy shotgun", "h en shotg" },
	{ "hurt enemy vehicle", "h en veh" },
	{ "hurt enemy mountedweapon", "h en mount" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "killed friend", "k fri" },
	{ "killed friend cm", "k fri cm" },
	{ "killed friend player", "k playr" },
	{ "killed friend player cm", "k playr cm" },
	{ "killed enemy", "k enemy" },
	{ "killed enemy cm", "k en cm" },
	{ "killed enemy player", "k en play" },
	{ "killed enemy player cm", "k en play cm" },
	{ "killed enemy covenant", "k cov" },
	{ "killed enemy covenant cm", "k cov cm" },
	{ "killed enemy floodcombat", "k flood" },
	{ "killed enemy floodcombat cm", "k flood cm" },
	{ "killed enemy floodcarrier", "k carrier" },
	{ "killed enemy floodcarrier cm", "k carrier cm" },
	{ "killed enemy sentinel", "k sent" },
	{ "killed enemy sentinel cm", "k sent cm" },
	{ "killed enemy bullet", "k en bull" },
	{ "killed enemy needler", "k en need" },
	{ "killed enemy plasma", "k en plas" },
	{ "killed enemy sniper", "k en snipe" },
	{ "killed enemy grenade", "k en gren" },
	{ "killed enemy explosion", "k en expl" },
	{ "killed enemy melee", "k en melee" },
	{ "killed enemy flame", "k en flame" },
	{ "killed enemy shotgun", "k en shotg" },
	{ "killed enemy vehicle", "k en veh" },
	{ "killed enemy mountedweapon", "k en mount" },
	{ "killing spree", "k spree" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "player kill cm", "pk cm" },
	{ "player kill bullet cm", "pk bull cm" },
	{ "player kill needler cm", "pk need cm" },
	{ "player kill plasma cm", "pk plas cm" },
	{ "player kill sniper cm", "pk snipe cm" },
	{ "anyone kill grenade cm", "pk gren cm" },
	{ "player kill explosion cm", "pk expl cm" },
	{ "player kill melee cm", "pk melee cm" },
	{ "player kill flame cm", "pk flame cm" },
	{ "player kill shotgun cm", "pk shotg cm" },
	{ "player kill vehicle cm", "pk veh cm" },
	{ "player kill mountedweapon cm", "pk mount cm" },
	{ "player killing spree cm", "pk spree cm" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "friend died", "d fri" },
	{ "friend player died", "d playr" },
	{ "friend killed by friend", "d b fri" },
	{ "friend killed by friendly player", "d b playr" },
	{ "friend killed by enemy", "d b enemy" },
	{ "friend killed by enemy player", "d b en playr" },
	{ "friend killed by covenant", "d b cov" },
	{ "friend killed by flood", "d b flood" },
	{ "friend killed by sentinel", "d b sent" },
	{ "friend betrayed", "d betray" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "new combat alone", "en new" },
	{ "new enemy recent combat", "en recent" },
	{ "old enemy sighted", "en search" },
	{ "unexpected enemy", "en unex" },
	{ "dead friend found", "deadbody" },
	{ "alliance broken", "ally broken" },
	{ "alliance reformed", "ally reform" },
	{ "grenade throwing", "gre throw" },
	{ "grenade startle", "gre start" },
	{ "grenade sighted", "gre sight" },
	{ "grenade danger enemy", "gre enemy" },
	{ "grenade danger self", "gre self" },
	{ "grenade danger friend", "gre friend" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "new combat group re", "en group re" },
	{ "nea combat nearby re", "en nearby re" },
	{ "alert friend", "al nonc" },
	{ "alert friend re", "al nonc re" },
	{ "alert lost contact", "al lostcom" },
	{ "alert lost contact re", "al lost re" },
	{ "blocked", "blocked" },
	{ "blocked re", "blocked re" },
	{ "search start", "sea start" },
	{ "search query", "sea query" },
	{ "search query re", "sea query re" },
	{ "search report", "sea report" },
	{ "search abandon", "sea aband" },
	{ "search group abandon", "sea g-aband" },
	{ "uncover start", "unc start" },
	{ "uncover start re", "unc start re" },
	{ "advance", "advance" },
	{ "advance re", "advance re" },
	{ "retreat", "retreat" },
	{ "retreat re", "retreat re" },
	{ "cover", "cover" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "sighted friend player", "friend play" },
	{ "shooting", "shoot" },
	{ "shooting vehicle", "shoot veh" },
	{ "shooting berserk", "shoot brs" },
	{ "shooting group", "shoot grp" },
	{ "shooting traitor", "shoot trai" },
	{ "taunt", "taunt" },
	{ "taunt re", "taunt re" },
	{ "flee", "flee" },
	{ "flee re", "flee re" },
	{ "flee leader died", "flee ldr" },
	{ "attempted flee", "a-flee" },
	{ "attempted flee re", "a-flee re" },
	{ "lost contact", "lostcont" },
	{ "hiding finished", "hid finish" },
	{ "vehicle entry", "veh entry" },
	{ "vehicle exit", "veh exit" },
	{ "vehicle woohoo", "veh yeah" },
	{ "vehicle scared", "veh scare" },
	{ "vehicle collision", "veh collide" },
	{ "partially sighted", "part sight" },
	{ "nothing there", "part nothn" },
	{ "pleading", "pleading" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "surprise", "surpr" },
	{ "berserk", "bersk" },
	{ "melee attack", "melee" },
	{ "dive", "dive" },
	{ "uncover leap", "unc leap" },
	{ "leap attack", "leap att" },
	{ "resurrection", "resurrect" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "celebration", "celeb" },
	{ "check body enemy", "check en" },
	{ "check body friend", "check fri" },
	{ "shooting dead enemy", "sh corps" },
	{ "shooting dead enemy player", "sh corps ply" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "alone", "alone" },
	{ "unscathed", "unscathed" },
	{ "seriously wounded", "wounded" },
	{ "seriously wounded re", "wounded re" },
	{ "massacre", "massacre" },
	{ "massacre re", "massacre re" },
	{ "rout", "rout" },
	{ "rout re", "rout re" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "unused", "unused" },
	{ "unused", "unused" },
};

short const dialogue_vocalization_lookup[NUMBER_OF_DIALOGUE_VOCALIZATION_TYPES] =
{
	1, NONE, NONE, NONE, NONE, NONE, NONE, 6, 6, 6, NONE, 10,
	NONE, 12, 15, NONE, 14, 15, 14, 15, NONE, NONE, 21, NONE,
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, 29, NONE, NONE, NONE, 32,
	32, 32, 32, 32, 32, 32, 32, 32, 32, 32, NONE, NONE,
	NONE, NONE, NONE, 49, NONE, NONE, NONE, 53, 54, 53, 54, 53,
	54, 53, 54, 53, 54, 53, 53, 53, 53, 53, 53, 53,
	53, 53, 53, 53, NONE, NONE, NONE, NONE, NONE, 80, 80, 80,
	80, 80, 80, 80, 80, 80, 80, 80, 80, 93, 94, 95,
	NONE, 96, 96, 98, 96, 100, 100, 100, 100, NONE, NONE, NONE,
	108, 109, 108, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, 53, 112, 154, 191,
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
	NONE, NONE, NONE, NONE, 0,
};

/* ---------- public code */

char const *dialogue_get_vocalization_name(
	short vocalization_type,
	boolean abbreviated)
{
	char const *name = "<error>";

	if (vocalization_type >= 0 && vocalization_type < NUMBER_OF_DIALOGUE_VOCALIZATION_TYPES)
		name = dialogue_vocalization_type_name[vocalization_type][abbreviated];

	return name;
}

short dialogue_get_vocalization_type_by_name(
	char const *name)
{
	short vocalization_type = NONE;
	short index;

	for (index = 0; index < NUMBER_OF_DIALOGUE_VOCALIZATION_TYPES; index++)
	{
		if (csstrcmp(dialogue_vocalization_type_name[index][0], name) == 0)
		{
			vocalization_type = index;
			break;
		}
	}

	return vocalization_type;
}

