/*
RASTERIZER_HARDWARE_FORMAT_UTILITIES.H
*/

#ifndef __RASTERIZER_HARDWARE_FORMAT_UTILITIES_H
#define __RASTERIZER_HARDWARE_FORMAT_UTILITIES_H
#pragma once

#endif // __RASTERIZER_HARDWARE_FORMAT_UTILITIES_H
